#!/bin/sh

### BEGIN INIT INFO
# Provides:          dhtDaemon
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: dht22 daemon
# Description:       This daemon reads from gpio sensors (specifically
#                    the dht22), and logs the received data.
### END INIT INFO

# Author: Samuel Wehunt (sam.wehunt@gmail.com)

DESC="Daemon for monitoring dht22 sensors connected to the gpio pins"
DAEMON=/usr/sbin/dhtDaemon
PID_FILE=/var/run/dhtDaemon.pid
test -x ${DAEMON} || { echo "${DAEMON} not installed";
                       if [ "${1}" = "stop" ]; then exit 0;
                       else exit 5; fi; }

case ${1} in
    start)
        ${DAEMON}
    ;;
    stop)
        kill `cat ${PID_FILE}`
        rm -f /var/run/dhtDaemon.pid
    ;;
    restart)
        kill `cat ${PID_FILE}`
        ${DAEMON}
    ;;
    reload)
        echo "Option doesn't do anything sorry"
    ;;
    status)
        if [ -r ${PID_FILE} ];
        then
            echo "dhtDaemon running at pid: `cat ${PID_FILE}`";
        fi
    ;;
    *)
        echo "Usage: ${0} {start|stop|restart|reload|status}"
        exit 1
    ;;
esac
