
.PHONY: install
install:
	sudo cp index.html /var/www/html/index.html
	sudo cp htaccess /var/www/html/.htaccess
	sudo pip3 install matplotlib
	sudo cp plotDht.py /var/www/html/plotDht.py
	sudo cp cronGraph /etc/cron.d/cronGraph
